### ISSUE TITLE
display a preview thumbnail for pictures

### ISSUE THREAD

**Issue by xiaoxiang01a** [Qbject/obsidian-canvas-link-optimizer#1]
When inserting a lot of pictures, the canvas will consume a lot of resources. 
Can it  also display thumbnails for the pictures in order to optimize the speed？

**Comment by khaelar** [comment]
I'd like to avoid adding functionality that goes beyond plugin's name.

Actually, high resource consumption is an issue for a lot of types of notes (images, PDFs, videos). I had an idea to create sort of universal canvas optimizer plugin, but unfortunately I don't have enough time to tackle this kind of thing right now.
